server:
  port: 9512
 
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lshangyi?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC&serverTimezone=GMT%2b8
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
 
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

# 打印sql
logging:
  level:
     com.example.demo.dao : debug

